<?
echo json_encode(array(
    'data'=>array(
        array(
            'id'=>'Worspace1',
            'Name'=>'Name1',
            'Info'=>'load info here',
            'MaxShadows'=>'1',
            'access'=>array(
                'classes'=>array(
                    array(
                        'id'=>'Class1',
                        'read'=>true,
                        'write'=>false,
                        'create'=>false,
                        'update'=>false,
                        'rights'=>false,
                        'groupRights'=>false
                    ),
                    array(
                        'id'=>'Class2',
                        'read'=>true,
                        'write'=>true,
                        'create'=>true,
                        'update'=>true,
                        'rights'=>true,
                        'groupRights'=>true
                    )
                ),
                'group'=>array(array(
                    'id'=>'Group1',
                    'Name'=>'Groupname1',
                    'read'=>true,
                    'write'=>true,
                    'create'=>true,
                    'update'=>true,
                    'rights'=>true,
                    'groupRights'=>true
                )),
                'user'=>array(array(
                    'id'=>'User1',
                    'Username'=>'Username1',
                    'read'=>true,
                    'write'=>true,
                    'create'=>true,
                    'update'=>true,
                    'rights'=>true,
                    'groupRights'=>true
                ))
            )
        ),
        array(
            'id'=>'Worspace2',
            'Name'=>'Name2',
            'Info'=>'some info here 2',
            'MaxShadows'=>'123'
        )
    ),
    'total'=>20
));

